### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Juan1787346** [samleong123/vercel-php-clearkey-hex-base64-json#4]
hello can someone help me to convert these keys in json to the long key

I give an example

#KODIPROP:inputstreamaddon=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=mpd
#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey
#KODIPROP:inputstream.adaptive.license_key={"keys":[{"kty":"oct","kid":"AAOOjndYHprC98tX53TqyA","k":"UiZhk_vJxF7tb8hTCSYShg"}]}

to

#KODIPROP:inputstream.adaptive.license_key=2d846f13c5bd43f3a456d9e958447f17:47e59e0ccb28b0ffa7ce830fd2519539

**Comment by Juan1787346** [comment]
need help pls

**Comment by samleong123** [comment]
Unrelated issue

**Comment by Juan1787346** [comment]
but could you help me please I know it's not related but I thought you could help me
