### ISSUE TITLE
Multiple clearkeys

### ISSUE THREAD

**Issue by 1YZTOOAr** [samleong123/vercel-php-clearkey-hex-base64-json#5]
Is it possible to enhance the code and the API to enable the use of multiple keys through the link?

`{
  "keys": [
    {"kty": "oct", "kid": "03o4uKXtS92jLWhNa3Xj6Q", "k": "JYfHzCa0fb2XRQ/Tvtvemw"},
    {"kty": "oct", "kid": "rzmUV14pSgGKSRNV4I0e0A", "k": "lhoUk+dwMhuXR34oqV2tSQ"},
    {"kty": "oct", "kid": "Tjar2s0iSyiW9p2JwasuMw", "k": "uyNDaYkC8bhEJ6KS5ENyCA"},
    {"kty": "oct", "kid": "dsqUuGpTRJ+cySBGkWgwOA", "k": "8UItxro+9kxcxSWj7WcF6Q"}
  ]
}
`

Thanks you

**Comment by samleong123** [comment]
Hi, Multiple Key & Key ID is now supported. Please check it out [here](https://github.com/samleong123/vercel-php-clearkey-hex-base64-json/blob/main/multiple_key.md)
