### ISSUE TITLE
Modification Multiple Clearkeys

### ISSUE THREAD

**Issue by 1YZTOOAr** [samleong123/vercel-php-clearkey-hex-base64-json#6]
My apologies. When mentioning the error, I didn't take into account that a line is missing at the end:

Here is an example with 2 keys from another project:

https://m3ukodi.com/php/clearkey_hextobase64/results.php?keyid[]=49eb924ba998ca7fbbaee30dcef1ecb4&key[]=6e131b04b2e87598fb588ac205673698&keyid[]=49eb924ba998ca7fbbaee30dcef1ecb4&key[]=6e131b04b2e87598fb588ac205673698

you can put any text into [], to more easy generate scripts:

https://m3ukodi.com/php/clearkey_hextobase64/results.php?keyid[0]=49eb924ba998ca7fbbaee30dcef1ecb4&key[0]=6e131b04b2e87598fb588ac205673698&keyid[1]=49eb924ba998ca7fbbaee30dcef1ecb4&key[1]=6e131b04b2e87598fb588ac205673698

I believe the easiest way would be the following, so there is no need to modify all proyect:

https://vercel-php-clearkey-hex-base64-json.vercel.app/api/results.php?keyid=49eb924ba998ca7fbbaee30dcef1ecb4&key=6e131b04b2e87598fb588ac205673698&keyid=49eb924ba998ca7fbbaee30dcef1ecb4&key=6e131b04b2e87598fb588ac205673698

I believe that this way would be better to facilitate the automation of scripts that generate the API call and return the value to Tivimate and ott player.

https://vercel-php-clearkey-hex-base64-json.vercel.app/api/results.php?keyid[0]=49eb924ba998ca7fbbaee30dcef1ecb4&key[0]=6e131b04b2e87598fb588ac205673698&keyid[1]=49eb924ba998ca7fbbaee30dcef1ecb4&key[1]=6e131b04b2e87598fb588ac205673698

The JSON needs to be like this for OTT players to read it, such as Tivimate, for example, all in 1 line:

```json
{"keys":[{"kty":"oct","k":"bhMbBLLodZj7WIrCBWc2mA","kid":"SeuSS6mYyn-7ruMNzvHstA"},{"kty":"oct","k":"bhMbBLLodZj7WIrCBWc2mA","kid":"SeuSS6mYyn-7ruMNzvHstA"}],"type":"temporary"}
```

The maximum number of keys in Widevine is 5 groups of kid key.

I don't know PHP, otherwise, I would have gladly helped :)

Thank you very much for your project.

**Comment by samleong123** [comment]
Hi, the `"type":"temporary"` has been [added](https://github.com/samleong123/vercel-php-clearkey-hex-base64-json/commit/2fdc0fdbdf3873a3db35f16d269d549e5f7c5199) to the JSON output. OTT players should now be able to use and recognize this as the license URL.

Regarding the issue of providing Key ID and Key for generating the license URL, personally, I feel that using a JSON-formatted Key + Key ID string with Base64 encoding will be sufficient for providing 5 KID/Key pairs.

The reason I choose to use Base64 is that it doesn't look too messy in the query string of the URL and is easy to identify any missing parameters for the URL.

You can use Excel to provide the Key and Key ID in a format like the one below (save as CSV), and then head to [this link](https://www.convertcsv.com/csv-to-json.htm) to convert it to a JSON string. Afterward, encode it as Base64 [here](https://www.base64encode.org/).
![image](https://github.com/samleong123/vercel-php-clearkey-hex-base64-json/assets/58818070/3e6a2f2c-4cf5-4d41-844b-243172418657)

I hope this answers your question

**Comment by 1YZTOOAr** [comment]
What doesn't fully convince me about your multiple keys system is that if you have a CSV file with 270 channels, and each channel has 5 KID/Keys in the clear key, I have to send the keys with Python to the URL, which the API will then translate.

I cannot use external pages since I want to automate this process in Python. Let me explain a bit so you can see:

1. Create the JSON from the browser player.

```
[
  {
    "init_data": "psshh",
    "stream_url": [
      "url1.mpd",
      "url2.mpd",
    ]
  },
  {
    "kid": "0a5c3786ceba1345b24ce80161b9eb2f",
    "key": "326e0f41fb3761f08ecd98e8fdc6e6e6"
  },
  {
    "kid": "0a5c3786ceba1345b24ce80161b9eb2f",
    "key": "326e0f41fb3761f08ecd98e8fdc6e6e6"
  },
  {
    "kid": "0a5c3786ceba1345b24ce80161b9eb2f",
    "key": "326e0f41fb3761f08ecd98e8fdc6e6e6"
  }
]
```

2. With Python, I read the 270 JSON files and convert them into a CSV with the following structure:

  ` pshh;URL1;URL2;URL3;URL4;URL5;kid0;key0;kid1;key1;kid2;key2;kid3;key3;kid4;key4;kid5;key5;`

3. Same Script Combine the CSV with EXTINF information (logo, channel, etc.) I have generated from the operator's EPG.

4. Generate an OTT list.

Therefore, it's not a good idea if I have to depend on external web pages for the project to create the call URL, as doing it manually is not an option.

So that the API call URL should have the following fields, making it much easier to use in automation and not relying on external pages or human intervention for its creation:

`https://vercel-php-clearkey-hex-base64-json.vercel.app/api/results.php?keyid=49eb924ba998ca7fbbaee30dcef1ecb4&key=6e131b04b2e87598fb588ac205673698&keyid=49eb924ba998ca7fbbaee30dcef1ecb4&key=6e131b04b2e87598fb588ac205673698`

`https://vercel-php-clearkey-hex-base64-json.vercel.app/api/results.php?keyid[0]=49eb924ba998ca7fbbaee30dcef1ecb4&key[0]=6e131b04b2e87598fb588ac205673698&keyid[1]=49eb924ba998ca7fbbaee30dcef1ecb4&key[1]=6e131b04b2e87598fb588ac205673698`

**Comment by samleong123** [comment]
Issue closed due to my current lack of time to maintain this repository and the receipt of a [take down notice](https://github.com/samleong123/vercel-php-clearkey-hex-base64-json/blob/main/takedown-email.md).

If you wish to enhance the code, please feel free to open a Pull Request. I will review and approve it as soon as possible. Thank you.
